### ISSUE TITLE
Swagger integration

### ISSUE THREAD

**Issue by raicotop** [Flexiana/framework#208]
# Problem
It is not clear how to integrate swagger into a framework-based app. I've tried to do it, but was not successful. There are some swagger integration examples for ring/reitit based apps (https://github.com/metosin/reitit/blob/master/doc/ring/swagger.md), but since framework uses its custom ring handler, the sample code can't be simply copied & pasted.

# Solution
If swagger can be integrated somehow even with the current custom ring handler, a documentation explaining how to do it would be nice. Otherwise a proper support for swagger integration would be needed.

**Comment by LeaveNhA** [comment]
I crated an example-based solution, now I'm migrating that implementation to the Xiana.

**Comment by LeaveNhA** [comment]
This task is under review at #240.
