### ISSUE TITLE
Add support of Argon2 key derivation function to xiana/hash

### ISSUE THREAD

**Issue by puchka** [Flexiana/framework#232]
Argon2 is a key derivation function that was selected as the winner of the 2015 Password Hashing Competition.

# Reference

https://www.twelve21.io/how-to-use-argon2-for-password-hashing-in-java/

**Comment by gmsvalente** [comment]
Added the argon2 methods in https://github.com/Flexiana/crypto-password.
Can use as usual now with the key :argon2 for the argon2 hash methods.

**Comment by soulflyer** [comment]
Theo is working on this (https://github.com/theodor-meresescu)

**Comment by gmsvalente** [comment]
Good job Theodor!
