### ISSUE TITLE
PSQLException in db-access interceptor

### ISSUE THREAD

**Issue by agigao** [Flexiana/framework#239]
I and @LeaveNhA paired on the issue together and it turns out that sql generator function isn't executed before passing to `->sql-params` and hence we get the error:

```
exception org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of app.controllers.index$model_test. Use setObject() with an explicit Types value to specify the type to use.
```

Relevant documentation - https://github.com/Flexiana/framework/blob/main/doc/tutorials.md#action

```clojure
(defn action
  [state]
  (assoc state :view view/success
               :side-effect behaviour/update-sessions-and-db!
               :query model/fetch-query))

(defn fetch-query
  [state]
  (let [login (-> state :request :body-params :login)]
    (-> (select :*)
        (from :users)
        (where [:and
                :is_active
                [:or
                 [:= :email login]
                 [:= :username login]]]))))
```

----

Also, there's a very very interesting behaviour - in a controller when atom is defined and I try to access it after execution, only sometimes it records the state. Haven't figured out the reason behind this behaviour though.

**Comment by g-krisztian** [comment]
- `->sql-param` calls the `sql/format` fn, so it's parameter should be a map, and it should return with a vector with prepared query. 
- SQL exception seems to caused via wrong parameter, it should be a single sql type, nothing complex type. Be sure if the parameter you pass isn't a map, or collection.
- I have no idea :D for the atom. You should not to reload the namesace (neither from `user/restart-app`). Try to use `defonce`, and avoid defining it from the action. The action is defined as `var` in route, so I'm not sure what happens with your atom when you try dynamically solve it.

**Comment by agigao** [comment]
The 2nd point is related to the first one.

In the example we see a function `fetch-query` returns a map, but it's not executed in the action body.
So, the `->sql-param` receives a function reference instead of data from the executed function:

```
  datasource = { :connectable jdbc:postgresql://localhost:5433/app, :options { :return-keys true } }
  sql-map = app.controllers.index$model_test_q@364277c0
```

<img width="754" alt="Screenshot 2022-10-18 at 10 31 04" src="https://user-images.githubusercontent.com/22436648/196352963-4913421a-bdb1-4632-bd17-38c9a7900c0d.png">

---- 
Regarding the last point, it kinda gives me the idea and will test it.

**Comment by g-krisztian** [comment]
oh I see, you should execute the query, and passing the state to it. the documentation is misleading, I'll fix it. thx.

**Comment by LeaveNhA** [comment]
Please review my fix over the issue gentlemen.
