### ISSUE TITLE
Error when running example, artifact not found on Clojars

### ISSUE THREAD

**Issue by benjamin-asdf** [Flexiana/framework#246]
For instance go to dir framework/examples/controllers

```
lein run 
...
Could not find artifact com.flexiana:framework:jar:0.5.0-rc4 in central (https://repo1.maven.org/maven2/)
Could not find artifact com.flexiana:framework:jar:0.5.0-rc4 in clojars (https://repo.clojars.org/)
This could be due to a typo in :dependencies, file system permissions, or network issues.
```

If you are behind a proxy, try setting the 'http_proxy' environment variable.
works when I change it to rc-3, which is also the one I find on Clojars.

**Comment by g-krisztian** [comment]
Hey @benjamin-asdf !
Not all changes on the main branch deployed to clojars. If you want to test something you can install the actual version likewise it's wrote at [readme](https://github.com/Flexiana/framework/blob/main/doc/contribution.md#install-locally)

**Comment by benjamin-asdf** [comment]
I see thank you @g-krisztian! Its easy to miss this when going straight to the examples and try to run one.
