### ISSUE TITLE
Update ring version (they dropped servlet-api dependency)

### ISSUE THREAD

**Issue by agigao** [Flexiana/framework#258]
Hello team,

We need to bump up ring version, since they dropped `servlet-api` dependency and projects with latest libraries fail if `multipart` interceptor is used.

Upgrade notice: https://github.com/ring-clojure/ring#upgrade-notice

Example: [Frankie PR](https://github.com/Flexiana/Frankie/pull/1835/#issuecomment-1765518815)

**Comment by soulflyer** [comment]
Not sure I understand. The upgrade notie is for versions after 1.2 and we are already using 1.9
