### ISSUE TITLE
Make it easy for a Xiana app to turn off logging messages

### ISSUE THREAD

**Issue by soulflyer** [Flexiana/framework#282]
Xiana is "noisy" in apps built using it. It should be easy to turn this off, as we use timbre which can set logging levels. It looks like control of this level is set inside the xiana code but it should be set in the app.

**Comment by jiriknesl** [comment]
We should absolutely use just 1. Which one do we use more?

**Comment by gmsvalente** [comment]
- create a function that runs at system config time to set timbre log level
