### ISSUE TITLE
Feature Request - Add schema validation feature to the framework

### ISSUE THREAD

**Issue by kno3comma14** [Flexiana/framework#92]
**Feature Description**
Given that validation is a required step in the request life-cycle, I purpose to add a feature to the framework that uses [metosin/malli](https://github.com/metosin/malli) or [spec](https://clojure.org/guides/spec) to validate request/input schemas. With this approach, we are offering a possibility to the user to preserve data integrity.

**Solution**
Create a new namespace at ```framework.validation.core``` with validate and explain functions. These functions have to receive the schema expected and the input to be validated.

**Additional**
- We can think about doing multiple implementations of this feature, but all these libraries work with different data types. 
-  [Spec](https://clojure.org/guides/spec) is part of the Clojure ecosystem but [metosin/malli](https://github.com/metosin/malli) looks more readable to me.

**Comment by jiriknesl** [comment]
Yes please. Let's add malli.

**Comment by soulflyer** [comment]
Malli is included in the examples, ie for request and response validation. Schema validation is mostly dependant on the application and probably belongs there rather than in the framework?
